/*
 * This file is generated by jOOQ.
 */
package com.hieplp.url.common.repository.url;


import com.hieplp.url.common.repository.url.tables.Url;
import com.hieplp.url.common.repository.url.tables.records.UrlRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * shortenUrl.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UrlRecord> KEY_URL_PRIMARY = Internal.createUniqueKey(Url.URL, DSL.name("KEY_url_PRIMARY"), new TableField[]{Url.URL.URLID}, true);
}
