/*
 * This file is generated by jOOQ.
 */
package com.hieplp.url.common.repository.url;


import com.hieplp.url.common.repository.url.tables.Url;


/**
 * Convenience access to all tables in shortenUrl.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>shortenUrl.url</code>.
     */
    public static final Url URL = Url.URL;
}
