/*
 * This file is generated by jOOQ.
 */
package com.hieplp.url.repository.generate.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Url implements Serializable {

    private static final long serialVersionUID = 1L;

    private String urlid;
    private String shorturl;
    private String longurl;
    private String alias;
    private LocalDateTime expiredat;
    private Byte status;
    private String createdby;
    private LocalDateTime createdat;
    private String modifiedby;
    private LocalDateTime modifiedat;
    private Byte isdeleted;
    private String deletedby;
    private LocalDateTime deletedat;

    public Url() {
    }

    public Url(Url value) {
        this.urlid = value.urlid;
        this.shorturl = value.shorturl;
        this.longurl = value.longurl;
        this.alias = value.alias;
        this.expiredat = value.expiredat;
        this.status = value.status;
        this.createdby = value.createdby;
        this.createdat = value.createdat;
        this.modifiedby = value.modifiedby;
        this.modifiedat = value.modifiedat;
        this.isdeleted = value.isdeleted;
        this.deletedby = value.deletedby;
        this.deletedat = value.deletedat;
    }

    public Url(
            String urlid,
            String shorturl,
            String longurl,
            String alias,
            LocalDateTime expiredat,
            Byte status,
            String createdby,
            LocalDateTime createdat,
            String modifiedby,
            LocalDateTime modifiedat,
            Byte isdeleted,
            String deletedby,
            LocalDateTime deletedat
    ) {
        this.urlid = urlid;
        this.shorturl = shorturl;
        this.longurl = longurl;
        this.alias = alias;
        this.expiredat = expiredat;
        this.status = status;
        this.createdby = createdby;
        this.createdat = createdat;
        this.modifiedby = modifiedby;
        this.modifiedat = modifiedat;
        this.isdeleted = isdeleted;
        this.deletedby = deletedby;
        this.deletedat = deletedat;
    }

    /**
     * Getter for <code>shortenUrl.url.urlId</code>.
     */
    public String getUrlid() {
        return this.urlid;
    }

    /**
     * Setter for <code>shortenUrl.url.urlId</code>.
     */
    public Url setUrlid(String urlid) {
        this.urlid = urlid;
        return this;
    }

    /**
     * Getter for <code>shortenUrl.url.shortUrl</code>.
     */
    public String getShorturl() {
        return this.shorturl;
    }

    /**
     * Setter for <code>shortenUrl.url.shortUrl</code>.
     */
    public Url setShorturl(String shorturl) {
        this.shorturl = shorturl;
        return this;
    }

    /**
     * Getter for <code>shortenUrl.url.longUrl</code>.
     */
    public String getLongurl() {
        return this.longurl;
    }

    /**
     * Setter for <code>shortenUrl.url.longUrl</code>.
     */
    public Url setLongurl(String longurl) {
        this.longurl = longurl;
        return this;
    }

    /**
     * Getter for <code>shortenUrl.url.alias</code>.
     */
    public String getAlias() {
        return this.alias;
    }

    /**
     * Setter for <code>shortenUrl.url.alias</code>.
     */
    public Url setAlias(String alias) {
        this.alias = alias;
        return this;
    }

    /**
     * Getter for <code>shortenUrl.url.expiredAt</code>.
     */
    public LocalDateTime getExpiredat() {
        return this.expiredat;
    }

    /**
     * Setter for <code>shortenUrl.url.expiredAt</code>.
     */
    public Url setExpiredat(LocalDateTime expiredat) {
        this.expiredat = expiredat;
        return this;
    }

    /**
     * Getter for <code>shortenUrl.url.status</code>.
     */
    public Byte getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>shortenUrl.url.status</code>.
     */
    public Url setStatus(Byte status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>shortenUrl.url.createdBy</code>.
     */
    public String getCreatedby() {
        return this.createdby;
    }

    /**
     * Setter for <code>shortenUrl.url.createdBy</code>.
     */
    public Url setCreatedby(String createdby) {
        this.createdby = createdby;
        return this;
    }

    /**
     * Getter for <code>shortenUrl.url.createdAt</code>.
     */
    public LocalDateTime getCreatedat() {
        return this.createdat;
    }

    /**
     * Setter for <code>shortenUrl.url.createdAt</code>.
     */
    public Url setCreatedat(LocalDateTime createdat) {
        this.createdat = createdat;
        return this;
    }

    /**
     * Getter for <code>shortenUrl.url.modifiedBy</code>.
     */
    public String getModifiedby() {
        return this.modifiedby;
    }

    /**
     * Setter for <code>shortenUrl.url.modifiedBy</code>.
     */
    public Url setModifiedby(String modifiedby) {
        this.modifiedby = modifiedby;
        return this;
    }

    /**
     * Getter for <code>shortenUrl.url.modifiedAt</code>.
     */
    public LocalDateTime getModifiedat() {
        return this.modifiedat;
    }

    /**
     * Setter for <code>shortenUrl.url.modifiedAt</code>.
     */
    public Url setModifiedat(LocalDateTime modifiedat) {
        this.modifiedat = modifiedat;
        return this;
    }

    /**
     * Getter for <code>shortenUrl.url.isDeleted</code>.
     */
    public Byte getIsdeleted() {
        return this.isdeleted;
    }

    /**
     * Setter for <code>shortenUrl.url.isDeleted</code>.
     */
    public Url setIsdeleted(Byte isdeleted) {
        this.isdeleted = isdeleted;
        return this;
    }

    /**
     * Getter for <code>shortenUrl.url.deletedBy</code>.
     */
    public String getDeletedby() {
        return this.deletedby;
    }

    /**
     * Setter for <code>shortenUrl.url.deletedBy</code>.
     */
    public Url setDeletedby(String deletedby) {
        this.deletedby = deletedby;
        return this;
    }

    /**
     * Getter for <code>shortenUrl.url.deletedAt</code>.
     */
    public LocalDateTime getDeletedat() {
        return this.deletedat;
    }

    /**
     * Setter for <code>shortenUrl.url.deletedAt</code>.
     */
    public Url setDeletedat(LocalDateTime deletedat) {
        this.deletedat = deletedat;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Url (");

        sb.append(urlid);
        sb.append(", ").append(shorturl);
        sb.append(", ").append(longurl);
        sb.append(", ").append(alias);
        sb.append(", ").append(expiredat);
        sb.append(", ").append(status);
        sb.append(", ").append(createdby);
        sb.append(", ").append(createdat);
        sb.append(", ").append(modifiedby);
        sb.append(", ").append(modifiedat);
        sb.append(", ").append(isdeleted);
        sb.append(", ").append(deletedby);
        sb.append(", ").append(deletedat);

        sb.append(")");
        return sb.toString();
    }
}
