/*
 * This file is generated by jOOQ.
 */
package com.hieplp.url.repository.generate.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Url implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       urlid;
    private String        shorturl;
    private String        longurl;
    private Byte          status;
    private LocalDateTime createdat;
    private LocalDateTime modifiedat;

    public Url() {}

    public Url(Url value) {
        this.urlid = value.urlid;
        this.shorturl = value.shorturl;
        this.longurl = value.longurl;
        this.status = value.status;
        this.createdat = value.createdat;
        this.modifiedat = value.modifiedat;
    }

    public Url(
        Integer       urlid,
        String        shorturl,
        String        longurl,
        Byte          status,
        LocalDateTime createdat,
        LocalDateTime modifiedat
    ) {
        this.urlid = urlid;
        this.shorturl = shorturl;
        this.longurl = longurl;
        this.status = status;
        this.createdat = createdat;
        this.modifiedat = modifiedat;
    }

    /**
     * Getter for <code>shortenUrl.url.urlId</code>.
     */
    public Integer getUrlid() {
        return this.urlid;
    }

    /**
     * Setter for <code>shortenUrl.url.urlId</code>.
     */
    public Url setUrlid(Integer urlid) {
        this.urlid = urlid;
        return this;
    }

    /**
     * Getter for <code>shortenUrl.url.shortUrl</code>.
     */
    public String getShorturl() {
        return this.shorturl;
    }

    /**
     * Setter for <code>shortenUrl.url.shortUrl</code>.
     */
    public Url setShorturl(String shorturl) {
        this.shorturl = shorturl;
        return this;
    }

    /**
     * Getter for <code>shortenUrl.url.longUrl</code>.
     */
    public String getLongurl() {
        return this.longurl;
    }

    /**
     * Setter for <code>shortenUrl.url.longUrl</code>.
     */
    public Url setLongurl(String longurl) {
        this.longurl = longurl;
        return this;
    }

    /**
     * Getter for <code>shortenUrl.url.status</code>.
     */
    public Byte getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>shortenUrl.url.status</code>.
     */
    public Url setStatus(Byte status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>shortenUrl.url.createdAt</code>.
     */
    public LocalDateTime getCreatedat() {
        return this.createdat;
    }

    /**
     * Setter for <code>shortenUrl.url.createdAt</code>.
     */
    public Url setCreatedat(LocalDateTime createdat) {
        this.createdat = createdat;
        return this;
    }

    /**
     * Getter for <code>shortenUrl.url.modifiedAt</code>.
     */
    public LocalDateTime getModifiedat() {
        return this.modifiedat;
    }

    /**
     * Setter for <code>shortenUrl.url.modifiedAt</code>.
     */
    public Url setModifiedat(LocalDateTime modifiedat) {
        this.modifiedat = modifiedat;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Url (");

        sb.append(urlid);
        sb.append(", ").append(shorturl);
        sb.append(", ").append(longurl);
        sb.append(", ").append(status);
        sb.append(", ").append(createdat);
        sb.append(", ").append(modifiedat);

        sb.append(")");
        return sb.toString();
    }
}
