/*
 * This file is generated by jOOQ.
 */
package com.hieplp.url.common.repository.url.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class User implements Serializable {

    private static final long serialVersionUID = 1L;

    private String userid;
    private String username;
    private Byte status;
    private String createdby;
    private LocalDateTime createdat;
    private String modifiedby;
    private LocalDateTime modifiedat;

    public User() {
    }

    public User(User value) {
        this.userid = value.userid;
        this.username = value.username;
        this.status = value.status;
        this.createdby = value.createdby;
        this.createdat = value.createdat;
        this.modifiedby = value.modifiedby;
        this.modifiedat = value.modifiedat;
    }

    public User(
            String userid,
            String username,
            Byte status,
            String createdby,
            LocalDateTime createdat,
            String modifiedby,
            LocalDateTime modifiedat
    ) {
        this.userid = userid;
        this.username = username;
        this.status = status;
        this.createdby = createdby;
        this.createdat = createdat;
        this.modifiedby = modifiedby;
        this.modifiedat = modifiedat;
    }

    /**
     * Getter for <code>shortenUrl.user.userId</code>.
     */
    public String getUserid() {
        return this.userid;
    }

    /**
     * Setter for <code>shortenUrl.user.userId</code>.
     */
    public User setUserid(String userid) {
        this.userid = userid;
        return this;
    }

    /**
     * Getter for <code>shortenUrl.user.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>shortenUrl.user.username</code>.
     */
    public User setUsername(String username) {
        this.username = username;
        return this;
    }

    /**
     * Getter for <code>shortenUrl.user.status</code>.
     */
    public Byte getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>shortenUrl.user.status</code>.
     */
    public User setStatus(Byte status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>shortenUrl.user.createdBy</code>.
     */
    public String getCreatedby() {
        return this.createdby;
    }

    /**
     * Setter for <code>shortenUrl.user.createdBy</code>.
     */
    public User setCreatedby(String createdby) {
        this.createdby = createdby;
        return this;
    }

    /**
     * Getter for <code>shortenUrl.user.createdAt</code>.
     */
    public LocalDateTime getCreatedat() {
        return this.createdat;
    }

    /**
     * Setter for <code>shortenUrl.user.createdAt</code>.
     */
    public User setCreatedat(LocalDateTime createdat) {
        this.createdat = createdat;
        return this;
    }

    /**
     * Getter for <code>shortenUrl.user.modifiedBy</code>.
     */
    public String getModifiedby() {
        return this.modifiedby;
    }

    /**
     * Setter for <code>shortenUrl.user.modifiedBy</code>.
     */
    public User setModifiedby(String modifiedby) {
        this.modifiedby = modifiedby;
        return this;
    }

    /**
     * Getter for <code>shortenUrl.user.modifiedAt</code>.
     */
    public LocalDateTime getModifiedat() {
        return this.modifiedat;
    }

    /**
     * Setter for <code>shortenUrl.user.modifiedAt</code>.
     */
    public User setModifiedat(LocalDateTime modifiedat) {
        this.modifiedat = modifiedat;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(userid);
        sb.append(", ").append(username);
        sb.append(", ").append(status);
        sb.append(", ").append(createdby);
        sb.append(", ").append(createdat);
        sb.append(", ").append(modifiedby);
        sb.append(", ").append(modifiedat);

        sb.append(")");
        return sb.toString();
    }
}
