/*
 * This file is generated by jOOQ.
 */
package com.hieplp.url.repository.generate;


import com.hieplp.url.repository.generate.tables.Url;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Shortenurl extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>shortenUrl</code>
     */
    public static final Shortenurl SHORTENURL = new Shortenurl();

    /**
     * The table <code>shortenUrl.url</code>.
     */
    public final Url URL = Url.URL;

    /**
     * No further instances allowed
     */
    private Shortenurl() {
        super("shortenUrl", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Url.URL);
    }
}
