/*
 * This file is generated by jOOQ.
 */
package com.hieplp.url.repository.generate;


import com.hieplp.url.repository.generate.tables.Password;
import com.hieplp.url.repository.generate.tables.Url;
import com.hieplp.url.repository.generate.tables.User;


/**
 * Convenience access to all tables in shortenUrl.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>shortenUrl.password</code>.
     */
    public static final Password PASSWORD = Password.PASSWORD;

    /**
     * The table <code>shortenUrl.url</code>.
     */
    public static final Url URL = Url.URL;

    /**
     * The table <code>shortenUrl.user</code>.
     */
    public static final User USER = User.USER;
}
