/*
 * This file is generated by jOOQ.
 */
package com.hieplp.url.common.repository.statistic.tables.records;


import com.hieplp.url.common.repository.statistic.tables.History;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class HistoryRecord extends UpdatableRecordImpl<HistoryRecord> implements Record5<String, String, Byte, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached HistoryRecord
     */
    public HistoryRecord() {
        super(History.HISTORY);
    }

    /**
     * Create a detached, initialised HistoryRecord
     */
    public HistoryRecord(String historyid, String urlid, Byte socialtype, String createdby, LocalDateTime createdat) {
        super(History.HISTORY);

        setHistoryid(historyid);
        setUrlid(urlid);
        setSocialtype(socialtype);
        setCreatedby(createdby);
        setCreatedat(createdat);
    }

    /**
     * Getter for <code>shortenStatistic.history.historyId</code>.
     */
    public String getHistoryid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>shortenStatistic.history.historyId</code>.
     */
    public HistoryRecord setHistoryid(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>shortenStatistic.history.urlId</code>.
     */
    public String getUrlid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>shortenStatistic.history.urlId</code>.
     */
    public HistoryRecord setUrlid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>shortenStatistic.history.socialType</code>.
     */
    public Byte getSocialtype() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>shortenStatistic.history.socialType</code>.
     */
    public HistoryRecord setSocialtype(Byte value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>shortenStatistic.history.createdBy</code>.
     */
    public String getCreatedby() {
        return (String) get(3);
    }

    /**
     * Setter for <code>shortenStatistic.history.createdBy</code>.
     */
    public HistoryRecord setCreatedby(String value) {
        set(3, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>shortenStatistic.history.createdAt</code>.
     */
    public LocalDateTime getCreatedat() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>shortenStatistic.history.createdAt</code>.
     */
    public HistoryRecord setCreatedat(LocalDateTime value) {
        set(4, value);
        return this;
    }

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    @Override
    public Row5<String, String, Byte, String, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, String, Byte, String, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return History.HISTORY.HISTORYID;
    }

    @Override
    public Field<String> field2() {
        return History.HISTORY.URLID;
    }

    @Override
    public Field<Byte> field3() {
        return History.HISTORY.SOCIALTYPE;
    }

    @Override
    public Field<String> field4() {
        return History.HISTORY.CREATEDBY;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return History.HISTORY.CREATEDAT;
    }

    @Override
    public String component1() {
        return getHistoryid();
    }

    @Override
    public String component2() {
        return getUrlid();
    }

    @Override
    public Byte component3() {
        return getSocialtype();
    }

    @Override
    public String component4() {
        return getCreatedby();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedat();
    }

    @Override
    public String value1() {
        return getHistoryid();
    }

    @Override
    public String value2() {
        return getUrlid();
    }

    @Override
    public Byte value3() {
        return getSocialtype();
    }

    @Override
    public String value4() {
        return getCreatedby();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedat();
    }

    @Override
    public HistoryRecord value1(String value) {
        setHistoryid(value);
        return this;
    }

    @Override
    public HistoryRecord value2(String value) {
        setUrlid(value);
        return this;
    }

    @Override
    public HistoryRecord value3(Byte value) {
        setSocialtype(value);
        return this;
    }

    @Override
    public HistoryRecord value4(String value) {
        setCreatedby(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public HistoryRecord value5(LocalDateTime value) {
        setCreatedat(value);
        return this;
    }

    @Override
    public HistoryRecord values(String value1, String value2, Byte value3, String value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }
}
