/*
 * This file is generated by jOOQ.
 */
package com.hieplp.url.repository.generate.tables.records;


import com.hieplp.url.repository.generate.tables.Url;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UrlRecord extends UpdatableRecordImpl<UrlRecord> implements Record6<Integer, String, String, Byte, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>shortenUrl.url.urlId</code>.
     */
    public UrlRecord setUrlid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>shortenUrl.url.urlId</code>.
     */
    public Integer getUrlid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>shortenUrl.url.shortUrl</code>.
     */
    public UrlRecord setShorturl(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>shortenUrl.url.shortUrl</code>.
     */
    public String getShorturl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>shortenUrl.url.longUrl</code>.
     */
    public UrlRecord setLongurl(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>shortenUrl.url.longUrl</code>.
     */
    public String getLongurl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>shortenUrl.url.status</code>.
     */
    public UrlRecord setStatus(Byte value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>shortenUrl.url.status</code>.
     */
    public Byte getStatus() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>shortenUrl.url.createdAt</code>.
     */
    public UrlRecord setCreatedat(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>shortenUrl.url.createdAt</code>.
     */
    public LocalDateTime getCreatedat() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>shortenUrl.url.modifiedAt</code>.
     */
    public UrlRecord setModifiedat(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>shortenUrl.url.modifiedAt</code>.
     */
    public LocalDateTime getModifiedat() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, Byte, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, Byte, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Url.URL.URLID;
    }

    @Override
    public Field<String> field2() {
        return Url.URL.SHORTURL;
    }

    @Override
    public Field<String> field3() {
        return Url.URL.LONGURL;
    }

    @Override
    public Field<Byte> field4() {
        return Url.URL.STATUS;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Url.URL.CREATEDAT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Url.URL.MODIFIEDAT;
    }

    @Override
    public Integer component1() {
        return getUrlid();
    }

    @Override
    public String component2() {
        return getShorturl();
    }

    @Override
    public String component3() {
        return getLongurl();
    }

    @Override
    public Byte component4() {
        return getStatus();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedat();
    }

    @Override
    public LocalDateTime component6() {
        return getModifiedat();
    }

    @Override
    public Integer value1() {
        return getUrlid();
    }

    @Override
    public String value2() {
        return getShorturl();
    }

    @Override
    public String value3() {
        return getLongurl();
    }

    @Override
    public Byte value4() {
        return getStatus();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedat();
    }

    @Override
    public LocalDateTime value6() {
        return getModifiedat();
    }

    @Override
    public UrlRecord value1(Integer value) {
        setUrlid(value);
        return this;
    }

    @Override
    public UrlRecord value2(String value) {
        setShorturl(value);
        return this;
    }

    @Override
    public UrlRecord value3(String value) {
        setLongurl(value);
        return this;
    }

    @Override
    public UrlRecord value4(Byte value) {
        setStatus(value);
        return this;
    }

    @Override
    public UrlRecord value5(LocalDateTime value) {
        setCreatedat(value);
        return this;
    }

    @Override
    public UrlRecord value6(LocalDateTime value) {
        setModifiedat(value);
        return this;
    }

    @Override
    public UrlRecord values(Integer value1, String value2, String value3, Byte value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UrlRecord
     */
    public UrlRecord() {
        super(Url.URL);
    }

    /**
     * Create a detached, initialised UrlRecord
     */
    public UrlRecord(Integer urlid, String shorturl, String longurl, Byte status, LocalDateTime createdat, LocalDateTime modifiedat) {
        super(Url.URL);

        setUrlid(urlid);
        setShorturl(shorturl);
        setLongurl(longurl);
        setStatus(status);
        setCreatedat(createdat);
        setModifiedat(modifiedat);
    }
}
