/*
 * This file is generated by jOOQ.
 */
package com.hieplp.url.common.repository.user;


import com.hieplp.url.common.repository.user.tables.Password;
import com.hieplp.url.common.repository.user.tables.User;


/**
 * Convenience access to all tables in shortenUser.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>shortenUser.password</code>.
     */
    public static final Password PASSWORD = Password.PASSWORD;

    /**
     * The table <code>shortenUser.user</code>.
     */
    public static final User USER = User.USER;
}
