/*
 * This file is generated by jOOQ.
 */
package com.hieplp.url.repository.generate.tables.daos;


import com.hieplp.url.repository.generate.tables.Url;
import com.hieplp.url.repository.generate.tables.records.UrlRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UrlDao extends DAOImpl<UrlRecord, com.hieplp.url.repository.generate.tables.pojos.Url, Integer> {

    /**
     * Create a new UrlDao without any configuration
     */
    public UrlDao() {
        super(Url.URL, com.hieplp.url.repository.generate.tables.pojos.Url.class);
    }

    /**
     * Create a new UrlDao with an attached configuration
     */
    public UrlDao(Configuration configuration) {
        super(Url.URL, com.hieplp.url.repository.generate.tables.pojos.Url.class, configuration);
    }

    @Override
    public Integer getId(com.hieplp.url.repository.generate.tables.pojos.Url object) {
        return object.getUrlid();
    }

    /**
     * Fetch records that have <code>urlId BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.url.repository.generate.tables.pojos.Url> fetchRangeOfUrlid(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Url.URL.URLID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>urlId IN (values)</code>
     */
    public List<com.hieplp.url.repository.generate.tables.pojos.Url> fetchByUrlid(Integer... values) {
        return fetch(Url.URL.URLID, values);
    }

    /**
     * Fetch a unique record that has <code>urlId = value</code>
     */
    public com.hieplp.url.repository.generate.tables.pojos.Url fetchOneByUrlid(Integer value) {
        return fetchOne(Url.URL.URLID, value);
    }

    /**
     * Fetch records that have <code>shortUrl BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.url.repository.generate.tables.pojos.Url> fetchRangeOfShorturl(String lowerInclusive, String upperInclusive) {
        return fetchRange(Url.URL.SHORTURL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>shortUrl IN (values)</code>
     */
    public List<com.hieplp.url.repository.generate.tables.pojos.Url> fetchByShorturl(String... values) {
        return fetch(Url.URL.SHORTURL, values);
    }

    /**
     * Fetch records that have <code>longUrl BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.url.repository.generate.tables.pojos.Url> fetchRangeOfLongurl(String lowerInclusive, String upperInclusive) {
        return fetchRange(Url.URL.LONGURL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>longUrl IN (values)</code>
     */
    public List<com.hieplp.url.repository.generate.tables.pojos.Url> fetchByLongurl(String... values) {
        return fetch(Url.URL.LONGURL, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.url.repository.generate.tables.pojos.Url> fetchRangeOfStatus(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(Url.URL.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.hieplp.url.repository.generate.tables.pojos.Url> fetchByStatus(Byte... values) {
        return fetch(Url.URL.STATUS, values);
    }

    /**
     * Fetch records that have <code>createdAt BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.url.repository.generate.tables.pojos.Url> fetchRangeOfCreatedat(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Url.URL.CREATEDAT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>createdAt IN (values)</code>
     */
    public List<com.hieplp.url.repository.generate.tables.pojos.Url> fetchByCreatedat(LocalDateTime... values) {
        return fetch(Url.URL.CREATEDAT, values);
    }

    /**
     * Fetch records that have <code>modifiedAt BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hieplp.url.repository.generate.tables.pojos.Url> fetchRangeOfModifiedat(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Url.URL.MODIFIEDAT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>modifiedAt IN (values)</code>
     */
    public List<com.hieplp.url.repository.generate.tables.pojos.Url> fetchByModifiedat(LocalDateTime... values) {
        return fetch(Url.URL.MODIFIEDAT, values);
    }
}
