/*
 * This file is generated by jOOQ.
 */
package com.hieplp.url.common.repository.user.tables.records;


import com.hieplp.url.common.repository.user.tables.Password;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PasswordRecord extends UpdatableRecordImpl<PasswordRecord> implements Record3<String, byte[], byte[]> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached PasswordRecord
     */
    public PasswordRecord() {
        super(Password.PASSWORD);
    }

    /**
     * Create a detached, initialised PasswordRecord
     */
    public PasswordRecord(String userid, byte[] password, byte[] salt) {
        super(Password.PASSWORD);

        setUserid(userid);
        setPassword(password);
        setSalt(salt);
    }

    /**
     * Getter for <code>shortenUser.password.userId</code>.
     */
    public String getUserid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>shortenUser.password.userId</code>.
     */
    public PasswordRecord setUserid(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>shortenUser.password.password</code>.
     */
    public byte[] getPassword() {
        return (byte[]) get(1);
    }

    /**
     * Setter for <code>shortenUser.password.password</code>.
     */
    public PasswordRecord setPassword(byte[] value) {
        set(1, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>shortenUser.password.salt</code>.
     */
    public byte[] getSalt() {
        return (byte[]) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>shortenUser.password.salt</code>.
     */
    public PasswordRecord setSalt(byte[] value) {
        set(2, value);
        return this;
    }

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    @Override
    public Row3<String, byte[], byte[]> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, byte[], byte[]> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Password.PASSWORD.USERID;
    }

    @Override
    public Field<byte[]> field2() {
        return Password.PASSWORD.PASSWORD_;
    }

    @Override
    public Field<byte[]> field3() {
        return Password.PASSWORD.SALT;
    }

    @Override
    public String component1() {
        return getUserid();
    }

    @Override
    public byte[] component2() {
        return getPassword();
    }

    @Override
    public byte[] component3() {
        return getSalt();
    }

    @Override
    public String value1() {
        return getUserid();
    }

    @Override
    public byte[] value2() {
        return getPassword();
    }

    @Override
    public byte[] value3() {
        return getSalt();
    }

    @Override
    public PasswordRecord value1(String value) {
        setUserid(value);
        return this;
    }

    @Override
    public PasswordRecord value2(byte[] value) {
        setPassword(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public PasswordRecord value3(byte[] value) {
        setSalt(value);
        return this;
    }

    @Override
    public PasswordRecord values(String value1, byte[] value2, byte[] value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
