version: '3.6'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elastic/elasticsearch:8.7.1
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic
    networks:
      - elastic
    ports:
      - '9200:9200'
      - '9300:9300'

  kibana:
    container_name: kibana
    image: elastic/kibana:8.7.1
    restart: always
    ports:
      - '5601:5601'
    networks:
      - elastic
    depends_on:
      - elasticsearch

  logstash:
    container_name: logstash
    build: ./logstash
    restart: always
    ports:
      - '9600:9600'
    networks:
      - elastic
    depends_on:
      - elasticsearch

networks:
  elastic:
    driver: bridge
