/*
 * This file is generated by jOOQ.
 */
package com.hieplp.url.common.repository.statistic.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class History implements Serializable {

    private static final long serialVersionUID = 1L;

    private String historyid;
    private String urlid;
    private Byte socialtype;
    private String createdby;
    private LocalDateTime createdat;

    public History() {
    }

    public History(History value) {
        this.historyid = value.historyid;
        this.urlid = value.urlid;
        this.socialtype = value.socialtype;
        this.createdby = value.createdby;
        this.createdat = value.createdat;
    }

    public History(
            String historyid,
            String urlid,
            Byte socialtype,
            String createdby,
            LocalDateTime createdat
    ) {
        this.historyid = historyid;
        this.urlid = urlid;
        this.socialtype = socialtype;
        this.createdby = createdby;
        this.createdat = createdat;
    }

    /**
     * Getter for <code>shortenStatistic.history.historyId</code>.
     */
    public String getHistoryid() {
        return this.historyid;
    }

    /**
     * Setter for <code>shortenStatistic.history.historyId</code>.
     */
    public History setHistoryid(String historyid) {
        this.historyid = historyid;
        return this;
    }

    /**
     * Getter for <code>shortenStatistic.history.urlId</code>.
     */
    public String getUrlid() {
        return this.urlid;
    }

    /**
     * Setter for <code>shortenStatistic.history.urlId</code>.
     */
    public History setUrlid(String urlid) {
        this.urlid = urlid;
        return this;
    }

    /**
     * Getter for <code>shortenStatistic.history.socialType</code>.
     */
    public Byte getSocialtype() {
        return this.socialtype;
    }

    /**
     * Setter for <code>shortenStatistic.history.socialType</code>.
     */
    public History setSocialtype(Byte socialtype) {
        this.socialtype = socialtype;
        return this;
    }

    /**
     * Getter for <code>shortenStatistic.history.createdBy</code>.
     */
    public String getCreatedby() {
        return this.createdby;
    }

    /**
     * Setter for <code>shortenStatistic.history.createdBy</code>.
     */
    public History setCreatedby(String createdby) {
        this.createdby = createdby;
        return this;
    }

    /**
     * Getter for <code>shortenStatistic.history.createdAt</code>.
     */
    public LocalDateTime getCreatedat() {
        return this.createdat;
    }

    /**
     * Setter for <code>shortenStatistic.history.createdAt</code>.
     */
    public History setCreatedat(LocalDateTime createdat) {
        this.createdat = createdat;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("History (");

        sb.append(historyid);
        sb.append(", ").append(urlid);
        sb.append(", ").append(socialtype);
        sb.append(", ").append(createdby);
        sb.append(", ").append(createdat);

        sb.append(")");
        return sb.toString();
    }
}
