/*
 * This file is generated by jOOQ.
 */
package com.hieplp.url.common.repository.statistic;


import com.hieplp.url.common.repository.statistic.tables.History;
import com.hieplp.url.common.repository.statistic.tables.records.HistoryRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * shortenStatistic.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<HistoryRecord> KEY_HISTORY_PRIMARY = Internal.createUniqueKey(History.HISTORY, DSL.name("KEY_history_PRIMARY"), new TableField[]{History.HISTORY.HISTORYID}, true);
}
