/*
 * This file is generated by jOOQ.
 */
package com.hieplp.url.common.repository.statistic;


import com.hieplp.url.common.repository.statistic.tables.History;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Shortenstatistic extends SchemaImpl {

    /**
     * The reference instance of <code>shortenStatistic</code>
     */
    public static final Shortenstatistic SHORTENSTATISTIC = new Shortenstatistic();
    private static final long serialVersionUID = 1L;
    /**
     * The table <code>shortenStatistic.history</code>.
     */
    public final History HISTORY = History.HISTORY;

    /**
     * No further instances allowed
     */
    private Shortenstatistic() {
        super("shortenStatistic", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
                History.HISTORY);
    }
}
