/*
 * This file is generated by jOOQ.
 */
package com.hieplp.url.common.repository.statistic;


import com.hieplp.url.common.repository.statistic.tables.History;


/**
 * Convenience access to all tables in shortenStatistic.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>shortenStatistic.history</code>.
     */
    public static final History HISTORY = History.HISTORY;
}
